baseURL = "https://www.raphaelluckom.com"
languageCode = "en-us"
title = "Raphael Luckom"
theme = "black-and-light"
publishDir = "./site"
canonifyURLs = true
uglyURLs = true
pygmentsCodeFences = true
pygmentsUseClassic = true
pygmentsStyle = "xcode"
[author]
   name = "Raphael Luckom"       #Author name
   github = "RLuckom"     #Github username
   linkedin = "raphaelluckom"   #LinkedIn username

[params]
  sitename = "Raphael Luckom"
  disableWebFonts = false
  customCss = ["css/style-overrides.css"]

[[menu.main]]
    name = "Github rluckom"
    title = "The public repositories containing the code of this website, other cloud infrastructure, and various tools and libraries"
    url  = "https://github.com/RLuckom"
