baseURL = "https://www.raphaelluckom.com"
languageCode = "en-us"
title = "Raphael Luckom"
theme = "black-and-light"
publishDir = "./site"
canonifyURLs = true
uglyURLs = true
pygmentsCodeFences = true
pygmentsUseClassic = true
pygmentsStyle = "xcode"
[author]
   name = "Raphael Luckom"       #Author name
   github = "RLuckom"     #Github username
   linkedin = "raphaelluckom"   #LinkedIn username

[params]
  sitename = "Raphael Luckom"
  disableWebFonts = false
  customCss = ["css/style-overrides.css"]

[[menu.main]]
    name = "Github rluckom"
    title = "The public repositories containing the code of this website, other cloud infrastructure, and various tools and libraries"
    url  = "https://github.com/RLuckom"
    weight = 10

[[menu.main]]
    name = "Stanford Encyclopedia of Philosophy"
    title = "Excellent reference on philosophy"
    url  = "https://plato.stanford.edu/index.html"
    weight = 90

[[menu.main]]
    name = "Philosophize This!"
    title = "Great podcast on philosophy"
    url  = "https://www.philosophizethis.org/"
    weight = 91


[[menu.main]]
    name = "Not Another D&D Podcast"
    title = "Comedy Dungeons & Dragons Podcast"
    url  = "https://www.naddpod.com/"
    weight = 92

[[menu.main]]
    name = "Lodash"
    title = "Documentation for one of the two most useful JavaScript libraries ever written"
    url  = "https://lodash.com/docs"
    weight = 100

[[menu.main]]
    name = "Async"
    title = "Documentation for the other of the two most useful JavaScript libraries ever written"
    url  = "https://caolan.github.io/async"
    weight = 101

[[menu.main]]
    name = "Online Regex Tester"
    title = "Useful regex tester"
    url  = "https://regex101.com/"
    weight = 110
